main: blackout.quake.main.Main
name: QuakeTest
version: 0.1
api-version: 1.13
author: Blackoutburst
description: A quake test
commands:
  lobby:
    description: Teleport you to spawn
    usage: /lobby
  l:
    description: Teleport you to spawn
    usage: /l
  spawn:
    description: Teleport you to spawn
    usage: /spawn
  listmap:
    description: List worlds and number of spawns
    usage: /listmap
  boop:
    description: Boop someone
    usage: /boop <player>
  start:
    description: Start the game
    usage: /start <world name>
  end:
    description: End the game
    usage: /end
  triggerSpeed:
    description: Set the trigger speed
    usage: /triggerspeed <value>
  maxScore:
    description: Set the max score
    usage: /maxscore <value>
  dashDelay:
    description: Set the dash delay
    usage: /dashdelay <value>
  playerSpeed:
    description: Set the player speed
    usage: /playerspeed <value>
  playerJump:
    description: Set the player jump
    usage: /playerjump <value>
  playerSlow:
    description: Set the player slowness
    usage: /playerslow <value>
  toggleBlindness:
    description: Toggle blindness
    usage: /toggleblindness
  toggleInvisibility:
    description: Toggle invisibility
    usage: /toggleinvisibility
  toggleNametag:
    description: Toggle nametag
    usage: /togglenametag
  toggleDash:
    description: Toggle dash
    usage: /toggledash
  toggleWalk:
    description: Toggle walk
    usage: /togglewalk
  toggleJump:
    description: Toggle jump
    usage: /togglejump
  resetConfig:
    description: Reset configuration
    usage: /resetconfig
  showConfig:
    description: Show configuration
    usage: /showconfig
  config:
    description: Show configuration menu
    usage: /config
  scan:
    permission: quake.debug
    description: Scan the world for gift spawnpoint (Debug command)
    usage: /scan <x1> <y1> <z1> <x2> <y2> <z2>
  loadSpawn:
    permission: quake.debug
    description: Load spawn point from file
    usage: /loadspawn
  clean:
    permission: quake.debug
    description: Clean spawn point
    usage: /clean
  showSpawn:
    permission: quake.debug
    description: Clean spawn point
    usage: /showspawn
    
  permissions:
    quake.debug:
      default: op