main: blackout.quake.main.Main
name: QuakeTest
version: 0.1
api-version: 1.13
author: Blackoutburst
description: A quake test
commands:
  start:
    description: Start the game
    usage: /start <world name>
  end:
    description: End the game
    usage: /end
  scan:
    description: Scan the world for gift spawnpoint (Debug command)
    usage: /scan <x1> <y1> <z1> <x2> <y2> <z2>
  loadSpawn:
    description: Load spawn point from file
    usage: /loadspawn
  clean:
    description: Clean spawn point
    usage: /clean
  showSpawn:
    description: Clean spawn point
    usage: /showspawn